### ISSUE TITLE
free(): invalid pointer: 0x000000000221e730 after changing level

### ISSUE THREAD

**Issue by Wuzzy2** [the-butterfly-effect/tbe#234]
I was testing f973aa28a0130b8c0eb139c0746358c8381b7b9f in level Extreme Tux Racer. After I changed the level to something else (I guess it was Spare the balloon, but I am not sure), I got a crash.

Console log and backtrace from `gdb`:
```
*** Error in `/home/wuzzy/src/tbe/tbe/tbe': free(): invalid pointer: 0x000000000221e730 ***
======= Backtrace: =========
/usr/lib/libc.so.6(+0x6ed4b)[0x7ffff56a5d4b]
/usr/lib/libc.so.6(+0x74546)[0x7ffff56ab546]
/usr/lib/libc.so.6(+0x74d1e)[0x7ffff56abd1e]
/home/wuzzy/src/tbe/tbe/tbe(_ZN15b2DistanceJointD0Ev+0x24)[0x54aa8e]
/home/wuzzy/src/tbe/tbe/tbe(_ZN4GlueD2Ev+0xc6)[0x4d9f92]
/home/wuzzy/src/tbe/tbe/tbe(_ZN4GlueD0Ev+0x18)[0x4da002]
/home/wuzzy/src/tbe/tbe/tbe(_ZNSt15_Sp_counted_ptrIP14AbstractObjectLN9__gnu_cxx12_Lock_policyE2EE10_M_disposeEv+0x38)[0x4c720c]
/home/wuzzy/src/tbe/tbe/tbe(_ZNSt16_Sp_counted_baseILN9__gnu_cxx12_Lock_policyE2EE10_M_releaseEv+0x42)[0x4acd9c]
/home/wuzzy/src/tbe/tbe/tbe(_ZNSt14__shared_countILN9__gnu_cxx12_Lock_policyE2EED2Ev+0x27)[0x4ac94b]
/home/wuzzy/src/tbe/tbe/tbe(_ZNSt12__shared_ptrI14AbstractObjectLN9__gnu_cxx12_Lock_policyE2EED1Ev+0x1c)[0x4ac7d0]
/home/wuzzy/src/tbe/tbe/tbe(_ZNSt10shared_ptrI14AbstractObjectED1Ev+0x18)[0x4ac7ec]
/home/wuzzy/src/tbe/tbe/tbe(_ZN5WorldD1Ev+0x264)[0x4f6d12]
/home/wuzzy/src/tbe/tbe/tbe(_ZN5WorldD0Ev+0x18)[0x4f6ec2]
/home/wuzzy/src/tbe/tbe/tbe(_ZN5LevelD2Ev+0x10b)[0x4bc4cd]
/home/wuzzy/src/tbe/tbe/tbe(_ZN5LevelD0Ev+0x18)[0x4bc5d6]
/home/wuzzy/src/tbe/tbe/tbe(_ZN10MainWindow10purgeLevelEv+0x113)[0x526d5f]
/home/wuzzy/src/tbe/tbe/tbe(_ZN10MainWindow9loadLevelERK7QString+0xce)[0x524fb0]
/home/wuzzy/src/tbe/tbe/tbe[0x5455e7]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x959)[0x7ffff6527679]
/home/wuzzy/src/tbe/tbe/tbe(_ZN11ChooseLevel9loadLevelERK7QString+0x47)[0x542d0d]
/home/wuzzy/src/tbe/tbe/tbe(_ZN11ChooseLevel24on_pushButton_go_clickedEv+0xbc)[0x4ffe74]
/home/wuzzy/src/tbe/tbe/tbe(_ZN11ChooseLevel34on_theTreeWidget_itemDoubleClickedEv+0x18)[0x548198]
/home/wuzzy/src/tbe/tbe/tbe[0x542b10]
/home/wuzzy/src/tbe/tbe/tbe(_ZN11ChooseLevel11qt_metacallEN11QMetaObject4CallEiPPv+0x5c)[0x542c9e]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x687)[0x7ffff65273a7]
/usr/lib/libQt5Widgets.so.5(_ZN11QTreeWidget17itemDoubleClickedEP15QTreeWidgetItemi+0x50)[0x7ffff74ea670]
/usr/lib/libQt5Core.so.5(_ZN11QMetaObject8activateEP7QObjectiiPPv+0x959)[0x7ffff6527679]
/usr/lib/libQt5Widgets.so.5(_ZN17QAbstractItemView13doubleClickedERK11QModelIndex+0x35)[0x7ffff747c345]
/usr/lib/libQt5Widgets.so.5(_ZN9QTreeView21mouseDoubleClickEventEP11QMouseEvent+0x1ca)[0x7ffff74c430a]
/usr/lib/libQt5Widgets.so.5(_ZN7QWidget5eventEP6QEvent+0xb27)[0x7ffff7267ab7]
/usr/lib/libQt5Widgets.so.5(_ZN6QFrame5eventEP6QEvent+0x1e)[0x7ffff736373e]
/usr/lib/libQt5Widgets.so.5(_ZN17QAbstractItemView13viewportEventEP6QEvent+0x173)[0x7ffff7489153]
/usr/lib/libQt5Widgets.so.5(_ZN9QTreeView13viewportEventEP6QEvent+0x3c)[0x7ffff74c62dc]
/usr/lib/libQt5Core.so.5(_ZN23QCoreApplicationPrivate29sendThroughObjectEventFiltersEP7QObjectP6QEvent+0x111)[0x7ffff64f9fe1]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x75)[0x7ffff7222795]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x1027)[0x7ffff7228727]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7ffff64fa280]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate14sendMouseEventEP7QWidgetP11QMouseEventS1_S1_PS1_R8QPointerIS0_Eb+0x255)[0x7ffff7226ee5]
/usr/lib/libQt5Widgets.so.5(+0x1b42c3)[0x7ffff72812c3]
/usr/lib/libQt5Widgets.so.5(+0x1b6793)[0x7ffff7283793]
/usr/lib/libQt5Widgets.so.5(_ZN19QApplicationPrivate13notify_helperEP7QObjectP6QEvent+0x9c)[0x7ffff72227bc]
/usr/lib/libQt5Widgets.so.5(_ZN12QApplication6notifyEP7QObjectP6QEvent+0x25f)[0x7ffff722795f]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication15notifyInternal2EP7QObjectP6QEvent+0x110)[0x7ffff64fa280]
/usr/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate17processMouseEventEPN29QWindowSystemInterfacePrivate10MouseEventE+0x47f)[0x7ffff6a463cf]
/usr/lib/libQt5Gui.so.5(_ZN22QGuiApplicationPrivate24processWindowSystemEventEPN29QWindowSystemInterfacePrivate17WindowSystemEventE+0x135)[0x7ffff6a47ea5]
/usr/lib/libQt5Gui.so.5(_ZN22QWindowSystemInterface22sendWindowSystemEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0xbb)[0x7ffff6a2518b]
/usr/lib/libQt5XcbQpa.so.5(+0x6d080)[0x7fffecd8c080]
/usr/lib/libglib-2.0.so.0(g_main_context_dispatch+0x2a7)[0x7ffff4cecdd7]
/usr/lib/libglib-2.0.so.0(+0x4a040)[0x7ffff4ced040]
/usr/lib/libglib-2.0.so.0(g_main_context_iteration+0x2c)[0x7ffff4ced0ec]
/usr/lib/libQt5Core.so.5(_ZN20QEventDispatcherGlib13processEventsE6QFlagsIN10QEventLoop17ProcessEventsFlagEE+0x5f)[0x7ffff65506cf]
/usr/lib/libQt5Core.so.5(_ZN10QEventLoop4execE6QFlagsINS_17ProcessEventsFlagEE+0xfa)[0x7ffff64f846a]
/usr/lib/libQt5Core.so.5(_ZN16QCoreApplication4execEv+0x9c)[0x7ffff6500a0c]
/home/wuzzy/src/tbe/tbe/tbe(main+0xae9)[0x4caafa]
/usr/lib/libc.so.6(__libc_start_main+0xf1)[0x7ffff5657741]
/home/wuzzy/src/tbe/tbe/tbe(_start+0x29)[0x4ab029]
======= Memory map: ========
00400000-0061d000 r-xp 00000000 08:05 20858184                           /home/wuzzy/src/tbe/tbe/usr/games/tbe
0081d000-00828000 rw-p 0021d000 08:05 20858184                           /home/wuzzy/src/tbe/tbe/usr/games/tbe
00828000-0254a000 rw-p 00000000 00:00 0                                  [heap]
7fffcc000000-7fffcc021000 rw-p 00000000 00:00 0 
7fffcc021000-7fffd0000000 ---p 00000000 00:00 0 
7fffd4000000-7fffd4021000 rw-p 00000000 00:00 0 
7fffd4021000-7fffd8000000 ---p 00000000 00:00 0 
7fffd8bfa000-7fffd8c51000 r--p 00000000 08:03 2639347                    /usr/share/fonts/TTF/LiberationSans-Bold.ttf
7fffd8c61000-7fffd8ca5000 r--p 00000000 08:03 2635719                    /usr/share/fonts/OTF/FreeSansIlBold.otf
7fffd8ca5000-7fffd8d83000 r--p 00000000 08:03 2635721                    /usr/share/fonts/OTF/FreeSansIl.otf
7fffd8d83000-7fffd9503000 rw-s 00000000 00:05 19202067                   /SYSV00000000 (deleted)
7fffd9503000-7fffd95ee000 rw-p 00000000 00:00 0 
7fffd95f4000-7fffd9615000 rw-s 00000000 00:05 19431449                   /SYSV00000000 (deleted)
7fffd9615000-7fffd96a6000 rw-s 00000000 00:05 19398680                   /SYSV00000000 (deleted)
7fffd96a6000-7fffd96c2000 rw-s 00000000 00:05 19365911                   /SYSV00000000 (deleted)
7fffd96c2000-7fffd96d9000 rw-s 00000000 00:05 19333142                   /SYSV00000000 (deleted)
7fffd96d9000-7fffd96f3000 r--s 00000000 08:04 525543                     /var/cache/fontconfig/8d4af663993b81a124ee82e610bb31f9-le64.cache-7
7fffd96f3000-7fffd9745000 r--s 00000000 08:04 525547                     /var/cache/fontconfig/f6b893a7224233d96cb72fd88691c0b4-le64.cache-7
7fffd9745000-7fffd9788000 r--s 00000000 08:04 525545                     /var/cache/fontconfig/17090aa38d5c6f09fb8c5c354938f1d7-le64.cache-7
7fffd9788000-7fffd97cb000 r--s 00000000 08:04 525544                     /var/cache/fontconfig/df311e82a1a24c41a75c2c930223552e-le64.cache-7
7fffd97cb000-7fffd97d6000 r-xp 00000000 08:03 2100479                    /usr/lib/libnss_files-2.23.so
7fffd97d6000-7fffd99d5000 ---p 0000b000 08:03 2100479                    /usr/lib/libnss_files-2.23.so
7fffd99d5000-7fffd99d6000 r--p 0000a000 08:03 2100479                    /usr/lib/libnss_files-2.23.so
7fffd99d6000-7fffd99d7000 rw-p 0000b000 08:03 2100479                    /usr/lib/libnss_files-2.23.so
7fffd99d7000-7fffd99dd000 rw-p 00000000 00:00 0 
7fffd99dd000-7fffd99de000 ---p 00000000 00:00 0 
7fffd99de000-7fffda1de000 rw-p 00000000 00:00 0 
7fffda1de000-7fffda1e6000 r-xp 00000000 08:03 2136759                    /usr/lib/libpciaccess.so.0.11.1
7fffda1e6000-7fffda3e6000 ---p 00008000 08:03 2136759                    /usr/lib/libpciaccess.so.0.11.1
7fffda3e6000-7fffda3e7000 r--p 00008000 08:03 2136759                    /usr/lib/libpciaccess.so.0.11.1
7fffda3e7000-7fffda3e8000 rw-p 00009000 08:03 2136759                    /usr/lib/libpciaccess.so.0.11.1
7fffda3e8000-7fffda3f3000 r-xp 00000000 08:03 2118379                    /usr/lib/libdrm_radeon.so.1.0.1
7fffda3f3000-7fffda5f2000 ---p 0000b000 08:03 2118379                    /usr/lib/libdrm_radeon.so.1.0.1
7fffda5f2000-7fffda5f3000 r--p 0000a000 08:03 2118379                    /usr/lib/libdrm_radeon.so.1.0.1
7fffda5f3000-7fffda5f4000 rw-p 0000b000 08:03 2118379                    /usr/lib/libdrm_radeon.so.1.0.1
7fffda5f4000-7fffda5fb000 r-xp 00000000 08:03 2139781                    /usr/lib/libdrm_nouveau.so.2.0.0
7fffda5fb000-7fffda7fa000 ---p 00007000 08:03 2139781                    /usr/lib/libdrm_nouveau.so.2.0.0
7fffda7fa000-7fffda7fb000 r--p 00006000 08:03 2139781                    /usr/lib/libdrm_nouveau.so.2.0.0
7fffda7fb000-7fffda7fc000 rw-p 00007000 08:03 2139781                    /usr/lib/libdrm_nouveau.so.2.0.0
7fffda7fc000-7fffda81c000 r-xp 00000000 08:03 2139775                    /usr/lib/libdrm_intel.so.1.0.0
7fffda81c000-7fffdaa1b000 ---p 00020000 08:03 2139775                    /usr/lib/libdrm_intel.so.1.0.0
7fffdaa1b000-7fffdaa1c000 r--p 0001f000 08:03 2139775                    /usr/lib/libdrm_intel.so.1.0.0
7fffdaa1c000-7fffdaa1d000 rw-p 00020000 08:03 2139775                    /usr/lib/libdrm_intel.so.1.0.0
7fffdaa1d000-7fffdb025000 r-xp 00000000 08:03 6435623                    /usr/lib/xorg/modules/dri/i965_dri.so
7fffdb025000-7fffdb225000 ---p 00608000 08:03 6435623                    /usr/lib/xorg/modules/dri/i965_dri.so
7fffdb225000-7fffdb25b000 r--p 00608000 08:03 6435623                    /usr/lib/xorg/modules/dri/i965_dri.so
7fffdb25b000-7fffdb262000 rw-p 0063e000 08:03 6435623                    /usr/lib/xorg/modules/dri/i965_dri.so
7fffdb262000-7fffdb2d6000 rw-p 00000000 00:00 0 
7fffdb2d6000-7fffdb342000 rw-s 00000000 00:05 19169298                   /SYSV00000000 (deleted)
7fffdb342000-7fffdb39f000 r-xp 00000000 08:03 2126130                    /usr/lib/libwebp.so.6.0.0
7fffdb39f000-7fffdb59e000 ---p 0005d000 08:03 2126130                    /usr/lib/libwebp.so.6.0.0
7fffdb59e000-7fffdb59f000 r--p 0005c000 08:03 2126130                    /usr/lib/libwebp.so.6.0.0
7fffdb59f000-7fffdb5a0000 rw-p 0005d000 08:03 2126130                    /usr/lib/libwebp.so.6.0.0
7fffdb5a0000-7fffdb5a1000 rw-p 00000000 00:00 0 
7fffdb5a1000-7fffdb5a5000 r-xp 00000000 08:03 5251214                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fffdb5a5000-7fffdb7a5000 ---p 00004000 08:03 5251214                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fffdb7a5000-7fffdb7a6000 r--p 00004000 08:03 5251214                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fffdb7a6000-7fffdb7a7000 rw-p 00005000 08:03 5251214                    /usr/lib/qt/plugins/imageformats/libqwebp.so
7fffdb7a7000-7fffdb7ab000 r-xp 00000000 08:03 5251216                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fffdb7ab000-7fffdb9ab000 ---p 00004000 08:03 5251216                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fffdb9ab000-7fffdb9ac000 r--p 00004000 08:03 5251216                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fffdb9ac000-7fffdb9ad000 rw-p 00005000 08:03 5251216                    /usr/lib/qt/plugins/imageformats/libqwbmp.so
7fffdb9ad000-7fffdba29000 r-xp 00000000 08:03 2121176                    /usr/lib/libtiff.so.5.2.4
7fffdba29000-7fffdbc29000 ---p 0007c000 08:03 2121176                    /usr/lib/libtiff.so.5.2.4
7fffdbc29000-7fffdbc2a000 r--p 0007c000 08:03 2121176                    /usr/lib/libtiff.so.5.2.4
7fffdbc2a000-7fffdbc30000 rw-p 0007d000 08:03 2121176                    /usr/lib/libtiff.so.5.2.4
7fffdbc30000-7fffdbc31000 rw-p 00000000 00:00 0 
7fffdbc31000-7fffdbc38000 r-xp 00000000 08:03 5251212                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fffdbc38000-7fffdbe37000 ---p 00007000 08:03 5251212                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fffdbe37000-7fffdbe38000 r--p 00006000 08:03 5251212                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fffdbe38000-7fffdbe39000 rw-p 00007000 08:03 5251212                    /usr/lib/qt/plugins/imageformats/libqtiff.so
7fffdbe39000-7fffdbe3e000 r-xp 00000000 08:03 5251211                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fffdbe3e000-7fffdc03d000 ---p 00005000 08:03 5251211                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fffdc03d000-7fffdc03e000 r--p 00004000 08:03 5251211                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fffdc03e000-7fffdc03f000 rw-p 00005000 08:03 5251211                    /usr/lib/qt/plugins/imageformats/libqtga.so
7fffdc03f000-7fffdc044000 r-xp 00000000 08:03 5248525                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fffdc044000-7fffdc243000 ---p 00005000 08:03 5248525                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fffdc243000-7fffdc244000 r--p 00004000 08:03 5248525                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fffdc244000-7fffdc245000 rw-p 00005000 08:03 5248525                    /usr/lib/qt/plugins/imageformats/libqsvg.so
7fffdc245000-7fffdc29b000 r-xp 00000000 08:03 2121712                    /usr/lib/liblcms2.so.2.0.7
7fffdc29b000-7fffdc49a000 ---p 00056000 08:03 2121712                    /usr/lib/liblcms2.so.2.0.7
7fffdc49a000-7fffdc49b000 r--p 00055000 08:03 2121712                    /usr/lib/liblcms2.so.2.0.7
7fffdc49b000-7fffdc4a0000 rw-p 00056000 08:03 2121712                    /usr/lib/liblcms2.so.2.0.7
7fffdc4a0000-7fffdc50d000 r-xp 00000000 08:03 2123594                    /usr/lib/libmng.so.2.0.2
7fffdc50d000-7fffdc70d000 ---p 0006d000 08:03 2123594                    /usr/lib/libmng.so.2.0.2
7fffdc70d000-7fffdc710000 r--p 0006d000 08:03 2123594                    /usr/lib/libmng.so.2.0.2
7fffdc710000-7fffdc712000 rw-p 00070000 08:03 2123594                    /usr/lib/libmng.so.2.0.2
7fffdc712000-7fffdc718000 r-xp 00000000 08:03 5251217                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fffdc718000-7fffdc917000 ---p 00006000 08:03 5251217                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fffdc917000-7fffdc918000 r--p 00005000 08:03 5251217                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fffdc918000-7fffdc919000 rw-p 00006000 08:03 5251217                    /usr/lib/qt/plugins/imageformats/libqmng.so
7fffdc919000-7fffdc926000 r-xp 00000000 08:03 5248236                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fffdc926000-7fffdcb25000 ---p 0000d000 08:03 5248236                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fffdcb25000-7fffdcb26000 r--p 0000c000 08:03 5248236                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fffdcb26000-7fffdcb27000 rw-p 0000d000 08:03 5248236                    /usr/lib/qt/plugins/imageformats/libqjpeg.so
7fffdcb27000-7fffdcb7e000 r-xp 00000000 08:03 2120415                    /usr/lib/libjpeg.so.8.0.2
7fffdcb7e000-7fffdcd7e000 ---p 00057000 08:03 2120415                    /usr/lib/libjpeg.so.8.0.2
7fffdcd7e000-7fffdcd7f000 r--p 00057000 08:03 2120415                    /usr/lib/libjpeg.so.8.0.2
7fffdcd7f000-7fffdcd80000 rw-p 00058000 08:03 2120415                    /usr/lib/libjpeg.so.8.0.2
7fffdcd80000-7fffdcdcd000 r-xp 00000000 08:03 2121332                    /usr/lib/libjasper.so.1.0.0
7fffdcdcd000-7fffdcfcc000 ---p 0004d000 08:03 2121332                    /usr/lib/libjasper.so.1.0.0
7fffdcfcc000-7fffdcfcd000 r--p 0004c000 08:03 2121332                    /usr/lib/libjasper.so.1.0.0
7fffdcfcd000-7fffdcfd1000 rw-p 0004d000 08:03 2121332                    /usr/lib/libjasper.so.1.0.0
7fffdcfd1000-7fffdcfd8000 rw-p 00000000 00:00 0 
7fffdcfd8000-7fffdcfe0000 r-xp 00000000 08:03 5251215                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fffdcfe0000-7fffdd1df000 ---p 00008000 08:03 5251215                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fffdd1df000-7fffdd1e0000 r--p 00007000 08:03 5251215                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fffdd1e0000-7fffdd1e1000 rw-p 00008000 08:03 5251215                    /usr/lib/qt/plugins/imageformats/libqjp2.so
7fffdd1e1000-7fffdd1e7000 r-xp 00000000 08:03 5248238                    /usr/lib/qt/plugins/imageformats/libqico.so
7fffdd1e7000-7fffdd3e7000 ---p 00006000 08:03 5248238                    /usr/lib/qt/plugins/imageformats/libqico.so
7fffdd3e7000-7fffdd3e8000 r--p 00006000 08:03 5248238                    /usr/lib/qt/plugins/imageformats/libqico.so
7fffdd3e8000-7fffdd3e9000 rw-p 00007000 08:03 5248238                    /usr/lib/qt/plugins/imageformats/libqico.so
7fffdd3e9000-7fffdd3f2000 r-xp 00000000 08:03 5251210                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fffdd3f2000-7fffdd5f1000 ---p 00009000 08:03 5251210                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fffdd5f1000-7fffdd5f2000 r--p 00008000 08:03 5251210                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fffdd5f2000-7fffdd5f3000 rw-p 00009000 08:03 5251210                    /usr/lib/qt/plugins/imageformats/libqicns.so
7fffdd5f3000-7fffdd5f9000 r-xp 00000000 08:03 5248237                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fffdd5f9000-7fffdd7f9000 ---p 00006000 08:03 5248237                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fffdd7f9000-7fffdd7fa000 r--p 00006000 08:03 5248237                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fffdd7fa000-7fffdd7fb000 rw-p 00007000 08:03 5248237                    /usr/lib/qt/plugins/imageformats/libqgif.so
7fffdd7fb000-7fffdd806000 r-xp 00000000 08:03 5251213                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fffdd806000-7fffdda05000 ---p 0000b000 08:03 5251213                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fffdda05000-7fffdda06000 r--p 0000a000 08:03 5251213                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fffdda06000-7fffdda07000 rw-p 0000b000 08:03 5251213                    /usr/lib/qt/plugins/imageformats/libqdds.so
7fffdda07000-7fffdda96000 r--p 00000000 08:03 2629818                    /usr/share/fonts/TTF/FreeMono.ttf
7fffdda96000-7fffdda9c000 r-xp 00000000 08:03 2122789                    /usr/lib/libogg.so.0.8.2
7fffdda9c000-7fffddc9b000 ---p 00006000 08:03 2122789                    /usr/lib/libogg.so.0.8.2
7fffddc9b000-7fffddc9c000 r--p 00005000 08:03 2122789                    /usr/lib/libogg.so.0.8.2
7fffddc9c000-7fffddc9d000 rw-p 00006000 08:03 2122789                    /usr/lib/libogg.so.0.8.2
7fffddc9d000-7fffddcc8000 r-xp 00000000 08:03 2122795                    /usr/lib/libvorbis.so.0.4.8
7fffddcc8000-7fffddec8000 ---p 0002b000 08:03 2122795                    /usr/lib/libvorbis.so.0.4.8
7fffddec8000-7fffddec9000 r--p 0002b000 08:03 2122795                    /usr/lib/libvorbis.so.0.4.8
7fffddec9000-7fffddeca000 rw-p 0002c000 08:03 2122795                    /usr/lib/libvorbis.so.0.4.8
7fffddeca000-7fffddf41000 r-xp 00000000 08:03 2107293                    /usr/lib/libgmp.so.10.3.0
7fffddf41000-7fffde140000 ---p 00077000 08:03 2107293                    /usr/lib/libgmp.so.10.3.0
7fffde140000-7fffde141000 r--p 00076000 08:03 2107293                    /usr/lib/libgmp.so.10.3.0
7fffde141000-7fffde142000 rw-p 00077000 08:03 2107293                    /usr/lib/libgmp.so.10.3.0
7fffde142000-7fffde175000 r-xp 00000000 08:03 2114209                    /usr/lib/libhogweed.so.4.2
Thread 1 "tbe" received signal SIGABRT, Aborted.
0x00007ffff566a295 in raise () from /usr/lib/libc.so.6
(gdb) bt
#0  0x00007ffff566a295 in raise () from /usr/lib/libc.so.6
#1  0x00007ffff566b6da in abort () from /usr/lib/libc.so.6
#2  0x00007ffff56a5d50 in __libc_message () from /usr/lib/libc.so.6
#3  0x00007ffff56ab546 in malloc_printerr () from /usr/lib/libc.so.6
#4  0x00007ffff56abd1e in _int_free () from /usr/lib/libc.so.6
#5  0x000000000054aa8e in b2DistanceJoint::~b2DistanceJoint (this=0x221e730, __in_chrg=<optimized out>)
    at /home/wuzzy/src/tbe/tbe/src/./Box2D/Dynamics/Joints/b2DistanceJoint.h:67
#6  0x00000000004d9f92 in Glue::~Glue (this=0xbd4ff0, __in_chrg=<optimized out>) at /home/wuzzy/src/tbe/tbe/src/model/Glue.cpp:62
#7  0x00000000004da002 in Glue::~Glue (this=0xbd4ff0, __in_chrg=<optimized out>) at /home/wuzzy/src/tbe/tbe/src/model/Glue.cpp:64
#8  0x00000000004c720c in std::_Sp_counted_ptr<AbstractObject*, (__gnu_cxx::_Lock_policy)2>::_M_dispose (this=0x19c7280)
    at /usr/include/c++/6.1.1/bits/shared_ptr_base.h:372
#9  0x00000000004acd9c in std::_Sp_counted_base<(__gnu_cxx::_Lock_policy)2>::_M_release (this=0x19c7280) at /usr/include/c++/6.1.1/bits/shared_ptr_base.h:150
#10 0x00000000004ac94b in std::__shared_count<(__gnu_cxx::_Lock_policy)2>::~__shared_count (this=0x7fffffffc898, __in_chrg=<optimized out>)
    at /usr/include/c++/6.1.1/bits/shared_ptr_base.h:662
#11 0x00000000004ac7d0 in std::__shared_ptr<AbstractObject, (__gnu_cxx::_Lock_policy)2>::~__shared_ptr (this=0x7fffffffc890, __in_chrg=<optimized out>)
    at /usr/include/c++/6.1.1/bits/shared_ptr_base.h:928
#12 0x00000000004ac7ec in std::shared_ptr<AbstractObject>::~shared_ptr (this=0x7fffffffc890, __in_chrg=<optimized out>) at /usr/include/c++/6.1.1/bits/shared_ptr.h:93
#13 0x00000000004f6d12 in World::~World (this=0x18ab5c0, __in_chrg=<optimized out>) at /home/wuzzy/src/tbe/tbe/src/model/World.cpp:70
#14 0x00000000004f6ec2 in World::~World (this=0x18ab5c0, __in_chrg=<optimized out>) at /home/wuzzy/src/tbe/tbe/src/model/World.cpp:80
#15 0x00000000004bc4cd in Level::~Level (this=0xe21850, __in_chrg=<optimized out>) at /home/wuzzy/src/tbe/tbe/src/loadsave/Level.cpp:98
#16 0x00000000004bc5d6 in Level::~Level (this=0xe21850, __in_chrg=<optimized out>) at /home/wuzzy/src/tbe/tbe/src/loadsave/Level.cpp:107
#17 0x0000000000526d5f in MainWindow::purgeLevel (this=0x7fffffffe040) at /home/wuzzy/src/tbe/tbe/src/view/MainWindow.cpp:414
#18 0x0000000000524fb0 in MainWindow::loadLevel (this=0x7fffffffe040, aFileName=...) at /home/wuzzy/src/tbe/tbe/src/view/MainWindow.cpp:101
#19 0x00000000005455e7 in MainWindow::qt_static_metacall (_o=0x7fffffffe040, _c=QMetaObject::InvokeMetaMethod, _id=0, _a=0x7fffffffccf0)
    at /home/wuzzy/src/tbe/tbe/build/src/moc_MainWindow.cpp:270
#20 0x00007ffff6527679 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#21 0x0000000000542d0d in ChooseLevel::loadLevel (this=0xcf05d0, _t1=...) at /home/wuzzy/src/tbe/tbe/build/src/moc_ChooseLevel.cpp:144
#22 0x00000000004ffe74 in ChooseLevel::on_pushButton_go_clicked (this=0xcf05d0) at /home/wuzzy/src/tbe/tbe/src/view/ChooseLevel.cpp:145
#23 0x0000000000548198 in ChooseLevel::on_theTreeWidget_itemDoubleClicked (this=0xcf05d0) at /home/wuzzy/src/tbe/tbe/build/src/../../src/view/ChooseLevel.h:55
#24 0x0000000000542b10 in ChooseLevel::qt_static_metacall (_o=0xcf05d0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffcf20)
    at /home/wuzzy/src/tbe/tbe/build/src/moc_ChooseLevel.cpp:86
#25 0x0000000000542c9e in ChooseLevel::qt_metacall (this=0xcf05d0, _c=QMetaObject::InvokeMetaMethod, _id=1, _a=0x7fffffffcf20)
    at /home/wuzzy/src/tbe/tbe/build/src/moc_ChooseLevel.cpp:130
#26 0x00007ffff65273a7 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#27 0x00007ffff74ea670 in QTreeWidget::itemDoubleClicked(QTreeWidgetItem*, int) () from /usr/lib/libQt5Widgets.so.5
#28 0x00007ffff6527679 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#29 0x00007ffff747c345 in QAbstractItemView::doubleClicked(QModelIndex const&) () from /usr/lib/libQt5Widgets.so.5
#30 0x00007ffff74c430a in QTreeView::mouseDoubleClickEvent(QMouseEvent*) () from /usr/lib/libQt5Widgets.so.5
#31 0x00007ffff7267ab7 in QWidget::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#32 0x00007ffff736373e in QFrame::event(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#33 0x00007ffff7489153 in QAbstractItemView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#34 0x00007ffff74c62dc in QTreeView::viewportEvent(QEvent*) () from /usr/lib/libQt5Widgets.so.5
#35 0x00007ffff64f9fe1 in QCoreApplicationPrivate::sendThroughObjectEventFilters(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#36 0x00007ffff7222795 in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#37 0x00007ffff7228727 in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#38 0x00007ffff64fa280 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#39 0x00007ffff7226ee5 in QApplicationPrivate::sendMouseEvent(QWidget*, QMouseEvent*, QWidget*, QWidget*, QWidget**, QPointer<QWidget>&, bool) ()
   from /usr/lib/libQt5Widgets.so.5
#40 0x00007ffff72812c3 in ?? () from /usr/lib/libQt5Widgets.so.5
#41 0x00007ffff7283793 in ?? () from /usr/lib/libQt5Widgets.so.5
#42 0x00007ffff72227bc in QApplicationPrivate::notify_helper(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
#43 0x00007ffff722795f in QApplication::notify(QObject*, QEvent*) () from /usr/lib/libQt5Widgets.so.5
---Type <return> to continue, or q <return> to quit---q
Quit
(gdb) q
```

**Comment by kaa-ching** [comment]
Sorry, my mistake.
